---
# tasks file for packages
# - name: Upgrading all packages (Ubuntu/Debian)
#   apt:
#     upgrade: dist
#     update_cache: true
#   when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: Upgrading all packages (CentOS)
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

- name: Install a few more packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim
    - htop
    - lynis

- name: install python-pip
  apt:
    state: latest
    name: python3-pip

- name: Install `unattended-upgrades` package 
  package:
    name: unattended-upgrades
    state: latest
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: Copy the `20auto-upgrades` configuration file
  copy:
    src: ../templates/20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: Copy the `50unattended-upgrades` configuration file
  copy:
    src: ../templates/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

