---
# tasks file for iptables
- name: Install the 'iptables' package
  package:
    name: iptables
    state: latest

- name: Flush existing firewall rules
  iptables:
    flush: true
 
- name: Firewall rule - allow all loopback traffic
  iptables:
    action: append
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Firewall rule - allow established connections
  iptables: 
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Firewall rule - allow port ping traffic
  iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: icmp
 
- name: Firewall rule - allow port 22/SSH traffic
  iptables:
    chain: INPUT
    destination_port: 22
    jump: ACCEPT
    protocol: tcp

- name: Firewall rule - allow port 80/HTTP traffic
  iptables: 
    chain: INPUT
    destination_port: 80
    jump: ACCEPT
    protocol: tcp

- name: Firewall rule - allow port 8080/HTTP traffic
  iptables:
    chain: INPUT
    destination_port: 8080
    jump: ACCEPT
    protocol: tcp

- name: Firewall rule - allow 443/HTTPS traffic
  iptables:
    chain: INPUT
    destination_port: 443
    jump: ACCEPT
    protocol: tcp

# - name: Firewall rule - allow SMTP Plain & STARTTLS
#   iptables:
#     chain: INPUT
#     destination_port: 25
#     jump: ACCEPT
#     protocol: tcp

# - name: Firewall rule - allow IMAP Plain & STARTTLS
#   iptables:
#     chain: INPUT
#     destination_port: 143
#     jump: ACCEPT
#     protocol: tcp

# - name: Firewall rule - allow SMTP over SSL
#   iptables:
#     chain: INPUT
#     destination_port: 587
#     jump: ACCEPT
#     protocol: tcp

# - name: Firewall rule - allow IMAP over SSL
#   iptables:
#     chain: INPUT
#     destination_port: 993
#     jump: ACCEPT
#     protocol: tcp

- name: Firewall rule - allow Sieve filter admin 
  iptables:
    chain: INPUT
    destination_port: 4190
    jump: ACCEPT
    protocol: tcp

- name: Firewall rule - drop any traffic without role
  iptables:
    chain: INPUT
    jump: DROP

- name: Install `netfilter-persistent` && `iptables-persistent` packages
  package:
    name: "{{ item }}"
    state: present
  with_items: 
    - iptables-persistent
    - netfilter-persistent
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: Save iptables configuration
  shell: netfilter-persistent save

- name: Copy the disable firewall script
  copy:
    src: ../templates/disable_firewall.sh
    dest: "/home/{{ username }}/"
    owner: root
    group: root
    mode: 0744
